import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Button } from "@/components/ui/button";
import { Heart } from "@/components/icons/heart";
import Link from "next/link";
import cloudinary from "cloudinary";
import { Folder } from "./albums/page";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang="en"
			className="dark">
			<body className={inter.className}>
				<div className="border-b">
					<div className="flex h-16 items-center px-4 container mx-auto">
						<Image
							src="/images/album.png"
							width="50"
							height="50"
							alt="icon of this photo album app"
						/>
						Corvedale 365 Photo Album
						<div className="ml-auto flex items-center space-x-4">
							<Avatar>
								<AvatarImage
									src="/images/avatar.jpg"
									alt="corvedale365 avatar"
								/>
								<AvatarFallback>CN</AvatarFallback>
							</Avatar>
						</div>
					</div>
				</div>
			</body>
		</html>
	);
}
